<?php

/**
 * path 前端路由map 映射的地址
 * code 唯一标识，如果不填，默认为：str_replace("\/", "-", path);
 */
return ['routes' => [
    [
        "id" => 1,
        "parent_id" => 0,
        "level" => 1,
        "title" => "首页",
        "path" => "index",
        "code" => "index",
        "order" => 0,
        "icon" => null,
        "menu" => true,
        "cache" => false,
        "createdTime" => 1647570758,
        "updatedTime" => 1647570758,
        "permission" => null,
        "roles" => [],
        "children" => []
    ],
//    [
//        "id" => 2,
//        "parent_id" => 0,
//        "title" => "路由配置",
//        "path" => null,
//        "order" => 1,
//        "icon" => null,
//        "menu" => true,
//        "cache" => false,
//        "createdTime" => 1647570758,
//        "updatedTime" => 1647570758,
//        "permission" => null,
//        "roles" => [],
//        "children" => [
//            [
//                "id" => 3,
//                "parent_id" => 2,
//                "title" => "所有路由",
//                "path" => "vue-routers",
//                "order" => 2,
//                "icon" => null,
//                "menu" => true,
//                "cache" => false,
//                "createdTime" => 1647570758,
//                "updatedTime" => 1647570758,
//                "permission" => null,
//                "roles" => [],
//                "children" => []
//            ],
//            [
//                "id" => 4,
//                "parent_id" => 2,
//                "title" => "添加路由",
//                "path" => "vue-routers/create",
//                "order" => 3,
//                "icon" => null,
//                "menu" => true,
//                "cache" => false,
//                "createdTime" => 1647570758,
//                "updatedTime" => 1647570758,
//                "permission" => null,
//                "roles" => [],
//                "children" => []
//            ],
//            [
//                "id" => 5,
//                "parent_id" => 2,
//                "title" => "编辑路由",
//                "path" => "vue-routers/:id(\d+)/edit",
//                "order" => 4,
//                "icon" => null,
//                "menu" => false,
//                "cache" => false,
//                "createdTime" => 1647570758,
//                "updatedTime" => 1647570758,
//                "permission" => null,
//                "roles" => [],
//                "children" => []
//            ]
//        ]
//    ],
    [
        "id" => 100,
        "parent_id" => 0,
        "level" => 1,
        "title" => "合作方管理",
        "path" => null,
        "code" => "third-party-manage",
        "order" => 100,
        "icon" => null,
        "menu" => true,
        "cache" => false,
        "createdTime" => 1647570758,
        "updatedTime" => 1647570758,
        "permission" => null,
        "roles" => [],
        "children" => [
            [
                "id" => 1001,
                "parent_id" => 100,
                "level" => 2,
                "title" => "合作方",
                "path" => "third-party/index",
                "code" => "third-party-index",
                "order" => 1,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => [
                    [
                        "id" => 10010,
                        "parent_id" => 1001,
                        "level" => 3,
                        "title" => "添加合作方",
                        "path" => "third-party/create",
                        "code" => "third-party-create",
                        "order" => 7,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ],
                    [
                        "id" => 10011,
                        "parent_id" => 1001,
                        "level" => 3,
                        "title" => "重置key/secret",
                        "path" => "third-party/:id(\d+)/edit",
                        "code" => "third-party-edit",
                        "order" => 8,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ],
                    [
                        "id" => 10012,
                        "parent_id" => 1001,
                        "level" => 3,
                        "title" => "封禁合作方",
                        "path" => "third-party/lock",
                        "code" => "third-party-lock",
                        "order" => 7,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ],
                ]
            ]
        ],
    ],
    [
        "id" => 101,
        "parent_id" => 0,
        "level" => 1,
        "title" => "国标设备",
        "path" => null,
        "code" => "device",
        "order" => 100,
        "icon" => null,
        "menu" => true,
        "cache" => false,
        "createdTime" => 1647570758,
        "updatedTime" => 1647570758,
        "permission" => null,
        "roles" => [],
        "children" => [
            [
                "id" => 1000,
                "parent_id" => 101,
                "level" => 2,
                "title" => "设备认领",
                "path" => "device/bind",
                "code" => "device-bind",
                "order" => 1,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => [
                    [
                        "id" => 10000,
                        "parent_id" => 1000,
                        "level" => 3,
                        "title" => "绑定合作方",
                        "path" => "device/saveBind",
                        "code" => "device-save-bind",
                        "order" => 1,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ],
                ]
            ],
            [
                "id" => 1011,
                "parent_id" => 101,
                "level" => 2,
                "title" => "录像机",
                "path" => "device/nvr/index",
                "code" => "device-nvr-index",
                "order" => 1,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => [
                    [
                        "id" => 10110,
                        "parent_id" => 1011,
                        "level" => 3,
                        "title" => "编辑录像机",
                        "path" => "device/nvr/edit",
                        "code" => "device-nvr-edit",
                        "order" => 1,
                        "icon" => null,
                        "menu" => true,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ],
                    [
                        "id" => 101110,
                        "parent_id" => 1011,
                        "level" => 3,
                        "title" => "详情",
                        "path" => "device-nvr/:id(\d+)/show",
                        "code" => "device-nvr-show",
                        "order" => 1,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ],
                    [
                        "id" => 101120,
                        "parent_id" => 1011,
                        "level" => 3,
                        "title" => "查看通道",
                        "path" => "device-nvr/:id(\d+)/channels",
                        "code" => "device-nvr-channels",
                        "order" => 1,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ]
                ]
            ],
            [
                "id" => 1012,
                "parent_id" => 101,
                "level" => 2,
                "title" => "摄像头",
                "path" => "device/ipc/index",
                "code" => "device-ipc-index",
                "order" => 1,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => [
                    [
                        "id" => 10120,
                        "parent_id" => 101,
                        "level" => 3,
                        "title" => "监控预览",
                        "path" => "device/ipc/:id/play",
                        "code" => "device-ipc-play",
                        "order" => 1,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ],
                ]
            ],
            [
                "id" => 1013,
                "parent_id" => 101,
                "level" => 2,
                "title" => "视频广场",
                "path" => "device/videos",
                "code" => "device-videos",
                "order" => 2,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => [
                    [
                        "id" => 10130,
                        "parent_id" => 1013,
                        "level" => 3,
                        "title" => "播放",
                        "path" => "videos/:id/play",
                        "code" => "videos-play",
                        "order" => 1,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ],
                ]
            ],
            // [
            //     "id" => 1014,
            //     "parent_id" => 101,
            //     "level" => 2,
            //     "title" => "云台展示",
            //     "path" => "device/cloud-show",
            //     "code" => "device-cloud-show",
            //     "order" => 2,
            //     "icon" => null,
            //     "menu" => true,
            //     "cache" => false,
            //     "createdTime" => 1647570758,
            //     "updatedTime" => 1647570758,
            //     "permission" => null,
            //     "roles" => [],
            //     "children" => []
            // ]
        ],
    ],
    [
        "id" => 102,
        "parent_id" => 0,
        "level" => 1,
        "title" => "资源管理",
        "path" => null,
        "code" => "resource",
        "order" => 100,
        "icon" => null,
        "menu" => true,
        "cache" => false,
        "createdTime" => 1647570758,
        "updatedTime" => 1647570758,
        "permission" => null,
        "roles" => [],
        "children" => [
            [
                "id" => 1020,
                "parent_id" => 102,
                "level" => 2,
                "title" => "录像管理",
                "path" => "resource/record-plans",
                "code" => "resource-record-plans",
                "order" => 1,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => [
                    [
                        "id" => 10200,
                        "parent_id" => 1020,
                        "level" => 3,
                        "title" => "添加录像计划",
                        "path" => "resource/record-plans/create",
                        "code" => "record-plans-create",
                        "order" => 1,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ],
                    [
                        "id" => 10201,
                        "parent_id" => 1020,
                        "level" => 3,
                        "title" => "删除录像计划",
                        "path" => "resource/record-plans/:id/delete",
                        "code" => "record-plans-delete",
                        "order" => 1,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ],
                    [
                        "id" => 10202,
                        "parent_id" => 1020,
                        "level" => 3,
                        "title" => "编辑录像计划",
                        "path" => "resource/record-plans/:id/edit",
                        "code" => "record-plans-update",
                        "order" => 1,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ],
                    [
                        "id" => 10203,
                        "parent_id" => 1020,
                        "level" => 3,
                        "title" => "统计",
                        "path" => "resource/record-plans/:id/summary",
                        "code" => "record-plans-summary",
                        "order" => 1,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => []
                    ],
                    [
                        "id" => 10204,
                        "parent_id" => 1020,
                        "level" => 3,
                        "title" => "录像回放",
                        "path" => "resource/record-playback/:id/view",
                        "code" => "record-playback-view",
                        "order" => 1,
                        "icon" => null,
                        "menu" => false,
                        "cache" => false,
                        "createdTime" => 1647570758,
                        "updatedTime" => 1647570758,
                        "permission" => null,
                        "roles" => [],
                        "children" => [
                            [
                                "id" => 102032,
                                "parent_id" => 10203,
                                "level" => 4,
                                "title" => "删除录像",
                                "path" => "resource/record-playback/:id/delete",
                                "code" => "record-playback-delete",
                                "order" => 1,
                                "icon" => null,
                                "menu" => false,
                                "cache" => false,
                                "createdTime" => 1647570758,
                                "updatedTime" => 1647570758,
                                "permission" => null,
                                "roles" => [],
                                "children" => []
                            ],
                            [
                                "id" => 102033,
                                "parent_id" => 10203,
                                "level" => 4,
                                "title" => "停止录像",
                                "path" => "resource/record-playback/:id/stop",
                                "code" => "record-playback-stop",
                                "order" => 1,
                                "icon" => null,
                                "menu" => false,
                                "cache" => false,
                                "createdTime" => 1647570758,
                                "updatedTime" => 1647570758,
                                "permission" => null,
                                "roles" => [],
                                "children" => []
                            ],
                            [
                                "id" => 102034,
                                "parent_id" => 10203,
                                "level" => 4,
                                "title" => "开启录像",
                                "path" => "resource/record-playback/:id/start",
                                "code" => "record-playback-start",
                                "order" => 1,
                                "icon" => null,
                                "menu" => false,
                                "cache" => false,
                                "createdTime" => 1647570758,
                                "updatedTime" => 1647570758,
                                "permission" => null,
                                "roles" => [],
                                "children" => []
                            ]
                        ]
                    ],
                ]
            ],
            [
                "id" => 1021,
                "parent_id" => 102,
                "level" => 2,
                "title" => "视频截图",
                "path" => "resource/images",
                "code" => "resource-images",
                "order" => 2,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
            [
                "id" => 1022,
                "parent_id" => 102,
                "level" => 2,
                "title" => "报警信息",
                "path" => "resource/warnings",
                "code" => "resource-warnings",
                "order" => 2,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
            [
                "id" => 1023,
                "parent_id" => 102,
                "level" => 2,
                "title" => "直播记录",
                "path" => "resource/play-records",
                "code" => "resource-play-records",
                "order" => 2,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
        ],
    ],
    [
        "id" => 103,
        "parent_id" => 0,
        "level" => 1,
        "title" => "日志管理",
        "path" => null,
        "code" => "log",
        "order" => 100,
        "icon" => null,
        "menu" => true,
        "cache" => false,
        "createdTime" => 1647570758,
        "updatedTime" => 1647570758,
        "permission" => null,
        "roles" => [],
        "children" => [
            [
                "id" => 1030,
                "parent_id" => 103,
                "level" => 2,
                "title" => "系统日志",
                "path" => "log/system-logs",
                "code" => "log-system-logs",
                "order" => 1,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
//            [
//                "id" => 1031,
//                "parent_id" => 103,
//                "level" => 2,
//                "title" => "直播日志",
//                "path" => "log/live-logs",
//                "code" => "log-live-logs",
//                "order" => 2,
//                "icon" => null,
//                "menu" => true,
//                "cache" => false,
//                "createdTime" => 1647570758,
//                "updatedTime" => 1647570758,
//                "permission" => null,
//                "roles" => [],
//                "children" => []
//            ],
            [
                "id" => 1032,
                "parent_id" => 103,
                "level" => 2,
                "title" => "设备注册日志",
                "path" => "log/device-register-logs",
                "code" => "log-device-register-logs",
                "order" => 2,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
            [
                "id" => 1033,
                "parent_id" => 103,
                "level" => 2,
                "title" => "设备在线日志",
                "path" => "log/device-active-logs",
                "code" => "log-device-active-logs",
                "order" => 2,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
        ],
    ],
    [
        "id" => 6,
        "parent_id" => 0,
        "title" => "管理员管理",
        "level" => 1,
        "path" => null,
        "code" => "admin-manage",
        "order" => 5,
        "icon" => null,
        "menu" => true,
        "cache" => false,
        "createdTime" => 1647570758,
        "updatedTime" => 1647570758,
        "permission" => null,
        "roles" => [],
        "children" => [
            [
                "id" => 7,
                "parent_id" => 6,
                "level" => 2,
                "title" => "管理员列表",
                "path" => "user/users",
                "code" => "user-users",
                "order" => 6,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
            [
                "id" => 8,
                "parent_id" => 6,
                "level" => 2,
                "title" => "添加管理员",
                "path" => "user/create",
                "code" => "user-create",
                "order" => 7,
                "icon" => null,
                "menu" => false,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
            [
                "id" => 9,
                "parent_id" => 6,
                "title" => "编辑管理员",
                "level" => 2,
                "path" => "user/:id(\d+)/edit",
                "code" => "user-edit",
                "order" => 8,
                "icon" => null,
                "menu" => false,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
            [
                "id" => 8,
                "parent_id" => 6,
                "level" => 2,
                "title" => "封禁管理员",
                "path" => "user/lock",
                "code" => "user-lock",
                "order" => 7,
                "icon" => null,
                "menu" => false,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
        ]
    ],
    [
        "id" => 24,
        "parent_id" => 0,
        "level" => 1,
        "title" => "系统配置",
        "path" => null,
        "code" => "setting",
        "order" => 23,
        "icon" => null,
        "menu" => true,
        "cache" => false,
        "createdTime" => 1647570758,
        "updatedTime" => 1647570758,
        "permission" => null,
        "roles" => [],
        "children" => [
            [
                "id" => 240,
                "parent_id" => 24,
                "level" => 2,
                "title" => "站点配置",
                "path" => "setting/site",
                "code" => "setting-site",
                "order" => 22,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
            [
                "id" => 241,
                "parent_id" => 24,
                "level" => 2,
                "title" => "ip限制",
                "path" => "setting/ip-blacklist",
                "code" => "setting-ip-blacklist",
                "order" => 22,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
            [
                "id" => 242,
                "parent_id" => 24,
                "level" => 2,
                "title" => "信令服务网关",
                "path" => "setting/ak-server",
                "code" => "setting-ak-server",
                "order" => 22,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ],
            [
                "id" => 243,
                "parent_id" => 24,
                "level" => 2,
                "title" => "邮件配置",
                "path" => "setting/email",
                "code" => "setting-email",
                "order" => 22,
                "icon" => null,
                "menu" => true,
                "cache" => false,
                "createdTime" => 1647570758,
                "updatedTime" => 1647570758,
                "permission" => null,
                "roles" => [],
                "children" => []
            ]
        ],
    ]
]];